### ISSUE TITLE
possible bug found

### ISSUE THREAD

**Issue by JuanAntonioNazabal** [rm5248/JavaSerial#2]
Hello,
I used you library and had some problems when I was reading from the InputStream retrieved from the SerialPort and at the same time catched an InterruptedException. I believe that the problem is in the read method from the class BufferedSerialInputStream. When an InterruptedException is catched, you only print the exception but I believe that you should restore the interrupted status after catching InterruptedException. So, changing the code "e.printStackTrace();" with the following code "Thread.currentThread().interrupt();" seems to fix the problem.
Best regards,
Juanan

**Comment by rm5248** [comment]
Thanks!  It does look like that could cause a problem.  I have never encountered an InterruptedException before, so I just printed the stack trace without thinking about it too much.

Links for reference: 

- http://www.yegor256.com/2015/10/20/interrupted-exception.html
- http://www.ibm.com/developerworks/library/j-jtp05236/

**Comment by rm5248** [comment]
Okay, so I've taken a look at it, and there's a few things that we can do here to fix it.

1. Throw an IOException when an InterruptedException occurs.
2. Ignore it and attempt to read from the buffer again.

It seems that number 2 is the general way to do it using an InputStream.  What probably makes the most sense here is to have a flag on the SerialPort which allows you to choose between these two methods, with option number 2 being the default.  

I also noticed that at least on Windows, when the SerialPort is closed you will get an erroneous 0 back from the InputStream, instead of -1.  See issue #3 for more information on that.

**Comment by rm5248** [comment]
Should be fixed with 0.7.
